sudo: required
services:
  - docker
before_install:
  - docker image build -t hieple/complex -f ./client/Dockerfile.dev ./client
script:
  - docker container run hieple/complex npm run test -- --coverage
after_success:
  - docker image build -t hieple/multi-client ./client
  - docker image build -t hieple/multi-nginx ./nginx
  - docker image build -t hieple/multi-server ./server
  - docker image build -t hieple/multi-worker ./woker