language: generic
sudo: required
services:
  - docker
before_install:
  - docker image build -t hieple/client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true hieple/client npm test
after_success:
  - docker image build -t hieple/multi-client ./client
  - docker image build -t hieple/multi-nginx ./nginx
  - docker image build -t hieple/multi-server ./server
  - docker image build -t hieple/multi-worker ./woker
